language: "typescript"

reviews:
  profile: "thorough"
  request_changes_workflow: true   # ❌ block merge on issues
  high_level_summary: true
  poem: false

# ❗ This is NOT a monorepo
monorepo:
  enabled: false

paths:
  include:
    - "src/**"
    - "configs/**"
    - "*.ts"